class ProductsDonHang {
  final String id,
      shop_id,
      order_id,
      order_shop_id,
      product_id,
      code,
      quantity,
      price,
      created_at,
      status,
      sale_before_product,
      sale_before_shop,
      sale_buy_shop_coin,
      sale_buy_shop_money,
      sale_charity,
      sale_admin,
      sale,
      user_before_product,
      user_before_shop,
      name,
      avatar_path,
      avatar_name,
      weight,
      height,
      width,
      length,
      product_name,
      alias;

  ProductsDonHang(
      {this.id,
        this.shop_id,
        this.order_id,
        this.order_shop_id,
        this.product_id,
        this.code,
        this.quantity,
        this.price,
        this.created_at,
        this.status,
        this.sale_before_product,
        this.sale_before_shop,
        this.sale_buy_shop_coin,
        this.sale_buy_shop_money,
        this.sale_charity,
        this.sale_admin,
        this.sale,
        this.user_before_product,
        this.user_before_shop,
        this.name,
        this.avatar_path,
        this.avatar_name,
        this.weight,
        this.height,
        this.width,
        this.length,
        this.product_name,
        this.alias});

  static List<ProductsDonHang> parseProducts(productsjson){
    var list = productsjson['products'] as List;
    List<ProductsDonHang> prd = list.map((data) => ProductsDonHang.fromJson(data)).toList();
    return prd;
  }

  factory ProductsDonHang.fromJson(Map<String, dynamic> parsedjson) {
    return ProductsDonHang(
      id: parsedjson['id'].toString(),
      shop_id: parsedjson['shop_id'].toString(),
      order_id: parsedjson['order_id'].toString(),
      order_shop_id: parsedjson['order_shop_id'].toString(),
      product_id: parsedjson['product_id'].toString(),
      code: parsedjson['code'].toString(),
      quantity: parsedjson['quantity'].toString(),
      price: parsedjson['price'].toString(),
      created_at: parsedjson['created_at'].toString(),
      status: parsedjson['status'].toString(),
      sale_before_product: parsedjson['sale_before_product'].toString(),
      sale_before_shop: parsedjson['sale_before_shop'].toString(),
      sale_buy_shop_coin: parsedjson['sale_buy_shop_coin'].toString(),
      sale_buy_shop_money: parsedjson['sale_buy_shop_money'].toString(),
      sale_charity: parsedjson['sale_charity'].toString(),
      sale_admin: parsedjson['sale_admin'].toString(),
      sale: parsedjson['sale'].toString(),
      user_before_product: parsedjson['user_before_product'].toString(),
      user_before_shop: parsedjson['user_before_shop'].toString(),
      name: parsedjson['name'].toString(),
      avatar_path: parsedjson['avatar_path'].toString(),
      avatar_name: parsedjson['avatar_name'].toString(),
      weight: parsedjson['weight'].toString(),
      height: parsedjson['height'].toString(),
      width: parsedjson['width'].toString(),
      length: parsedjson['length'].toString(),
      product_name: parsedjson['product_name'].toString(),
      alias: parsedjson['alias'].toString(),
    );
  }
}
