class Product_thang {
  String id,
      brand,
      name,
      alisas,
      category_id,
      category_track,
      code,
      barcode,
      currency,
      quantity,
      status,
      avatar_path,
      avatar_name,
      avatar_id,
      isnew,
      ishot,
      viewed,
      created_at,
      updated_at,
      short_description,
      description,
      meta_title,
      meta_description,
      meta_keywords,
      dynamic_field,
      shop_id,
      status_quantity,
      rate_count,
      rate,
      flash_sale,
      price_range,
      quality_range,
      province_id,
      unit,
      weight,
      height,
      length,
      width,
      type,
      start_time,
      number_time,
      fee_ship,
      note_fee_ship,
      videos,
      admin_update,
      admin_update_time,
      ckedit_desc,
      status_affiliate,
      voso_connect,
      list_category,
      affiliate_gt_product,
      affiliate_m_v,
      affiliate_m_ov,
      affiliate_safe,
      affiliate_charity,
      pay_coin,
      order,
      shop_status_affiliate,
      latlng,
      text_price_market,
      text_price
  ;
  int price,price_market,check_in_cart;


  Product_thang({this.id,
      this.name,
      this.brand,
      this.alisas,
      this.category_id,
      this.category_track,
      this.code,
      this.barcode,
  this.currency,
  this.quantity,
  this.status,
  this.avatar_path,
  this.avatar_name,
  this.avatar_id,
  this.isnew,
  this.ishot,
  this.viewed,
  this.created_at,
  this.updated_at,
  this.short_description,
      this.description,
  this.meta_title,
  this.meta_description,
      this.meta_keywords,
      this.dynamic_field,
  this.shop_id,
  this.status_quantity,
  this.rate_count,
  this.rate,
  this.flash_sale,
  this. price_range,
  this.quality_range,
  this.province_id,
  this.unit,
  this.weight,
      this.height,
  this.length,
  this.width,
      this.type,
      this.start_time,
  this.number_time,
  this.fee_ship,
  this.note_fee_ship,
  this.videos,
  this.admin_update,
  this.admin_update_time,
  this.ckedit_desc,
      this.status_affiliate,
  this.voso_connect,
  this.list_category,
      this.affiliate_gt_product,
      this.affiliate_m_v,
  this.affiliate_m_ov,
  this.affiliate_safe,
  this.affiliate_charity,
  this.pay_coin,
  this.order,
  this.shop_status_affiliate,
  this.latlng,
      this.text_price_market,
  this. text_price,
  this.price,
      this.price_market,
      this.check_in_cart,}
      );
  factory Product_thang.fromJson(Map<String, dynamic> json,int i) {
    return Product_thang(
      id: json['data'][i]['id'],
      name: json['data'][i]['name'],
      brand: json['data'][i]['brand'],
      alisas: json['data'][i]['alisas'],
      category_id: json['data'][i]['category_id'],
      category_track: json['data'][i]['category_track'],
      code: json['data'][i]['code'],
      barcode: json['data'][i]['barcode'],
      currency: json['data'][i]['currency'],
      quantity: json['data'][i]['quantity'],
      status: json['data'][i]['status'],
      avatar_path: json['data'][i]['avatar_path'],
      avatar_name: json['data'][i]['avatar_name'],
      avatar_id: json['data'][i]['avatar_id'],
      isnew: json['data'][i]['isnew'],
      ishot: json['data'][i]['ishot'],
      viewed: json['data'][i]['viewed'],
      created_at: json['data'][i]['created_at'],
      updated_at: json['data'][i]['updated_at'],
      short_description: json['data'][i]['short_description'],
      description: json['data'][i]['description'],
      meta_title: json['data'][i]['meta_title'],
      meta_description: json['data'][i]['meta_description'],
      meta_keywords: json['data'][i]['meta_keywords'],
      dynamic_field: json['data'][i]['dynamic_field'],
      shop_id: json['data'][i]['shop_id'],
      status_quantity: json['data'][i]['status_quantity'],
      rate_count: json['data'][i]['rate_count'],
      rate: json['data'][i]['rate'],
      flash_sale: json['data'][i]['flash_sale'],
      price_range: json['data'][i]['price_range'],
      quality_range: json['data'][i]['quality_range'],
      province_id: json['data'][i]['province_id'],
      unit: json['data'][i]['unit'],
      weight: json['data'][i]['weight'],
      height: json['data'][i]['height'],
      length: json['data'][i]['length'],
      width: json['data'][i]['width'],
      type: json['data'][i]['type'],
      start_time: json['data'][i]['start_time'],
      number_time: json['data'][i]['number_time'],
      fee_ship: json['data'][i]['fee_ship'],
      note_fee_ship: json['data'][i]['note_fee_ship'],
      videos: json['data'][i]['videos'],
      admin_update: json['data'][i]['admin_update'],
      admin_update_time: json['data'][i]['admin_update_time'],
      ckedit_desc: json['data'][i]['ckedit_desc'],
      status_affiliate: json['data'][i]['status_affiliate'],
      voso_connect: json['data'][i]['voso_connect'],
      list_category: json['data'][i]['list_category'],
      affiliate_gt_product: json['data'][i]['affiliate_gt_product'],
      affiliate_m_v: json['data'][i]['affiliate_m_v'],
      affiliate_m_ov: json['data'][i]['affiliate_m_ov'],
      affiliate_safe: json['data'][i]['affiliate_safe'],
      affiliate_charity: json['data'][i]['affiliate_charity'],
      pay_coin: json['data'][i]['pay_coin'],
      order: json['data'][i]['order'],
      shop_status_affiliate: json['data'][i]['shop_status_affiliate'],
      latlng: json['data'][i]['latlng'],
      text_price_market: json['data'][i]['text_price_market'],
      text_price: json['data'][i]['text_price'],
      price: json['data'][i]['price'],
      price_market: json['data'][i]['price_market'],
      check_in_cart: json['data'][i]['check_in_cart'],

    );
  }
}
List<Product_thang> product_list=[];